
ALTER TABLE meta_daily_insights
  ADD COLUMN IF NOT EXISTS landing_page_views INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS leads_native INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS leads_landing_page INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS link_clicks INTEGER NOT NULL DEFAULT 0;

NOTIFY pgrst, 'reload schema';
